language: node_js
node_js:
  - 12

os:
  - linux
  - osx

addons:
  sonarcloud:
    organization: "h-sslefree"

script:
  - npm install
  - npm test

jobs:
  include:
    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: "true"
        script:
          - npx semantic-release
                
