language: node_js
node_js:
  - 12
os:
  - linux
  - osx
jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm test
      branches:
        except:
          - master
    - stage: release
      if: branch = master
      deploy:
        provider: script
        on:
          tags: true
          repo: h-sslefree/solrts
        skip_cleanup: "true"
        script:
          - npx semantic-release
        
