trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    displayName: 'Prepare'
    inputs:
      versionSpec: '12.x'
  - script: |
      npm install
      npm test
      npm build
    displayName: 'Build and test'
    condition: eq(variables['Build.Reason'], 'PullRequest')
  - script: npx semantic-release
    displayName: 'Release'
    condition: ne(variables['Build.Reason'], 'PullRequest')
    env:
      NPM_TOKEN: '$(NPM_TOKEN)'
      GH_TOKEN: '$(GH_TOKEN)'